[[feeds]]
position = 1
name = "Lobste.rs"
url = "https://lobste.rs"

[[feeds]]
position = 2
name = "Hacker News"
url = "https://news.ycombinator.com"

[[feeds]]
position = 3
name = "Reddit"
url = "https://www.reddit.com"

[[feeds]]
position = 4
name = "Feedly"
url = "https://feedly.com"

[[feeds]]
position = 5
name = "TechCrunch"
url = "https://techcrunch.com"